name = "task2wechat" # 替换为您的 Pages 项目名称
main = "functions/_worker.js" # 指向您的 Pages Function 文件

[vars]
# 如果您有其他环境变量，可以在这里定义

[[triggers.cron]]
crons = ["0/5 * * * *"] # 每小时的第0分钟执行一次 (示例 Cron 表达式)
# 您可以根据需求调整 Cron 表达式，例如：
# "0 0 * * *" 每天午夜零点执行
# "*/5 * * * *" 每5分钟执行一次
